## CS559: Homework #1-1

This is a part of Assignment #1 and this assignment is due on **9/16/2020 by 11:59 PM**. You are going to submit the assignment both in format of *ipynb* and *html*. The assignment should be own work and must not be shared between classmates. Try to avoid using built-in functions. 

This assignment is about linear algebra and is more focusing on implementing functions. 

### Problem 1
- Write a function `dot_product` to calculate the dot product of two 1 by n arrays. 
```
a = array([1, 2, 3, 4])
b = array([2, 3, 4, 5])
dot_product(a,b) = 40
```

In [81]:
import math
import numpy as np
from pprint import pformat

def dot_product(v1: np.ndarray, v2: np.ndarray) -> int:
    """ Calculates the dot product of two vectors """
    if max(v1.shape) == max(v2.shape) and (len(v1.shape) == 1 or min(v1.shape) == 1):
        if min(v1.shape) == 1:  #  Shape is column matrix
            v1 = v1.reshape(max(v1.shape))  # Reshape to row matrix for easier calculation
        if min(v2.shape) == 1:
            v2 = v2.reshape(max(v2.shape))
            
        total = 0
        for i in range(max(v1.shape)):
            total += v1[i] * v2[i]
        return total
    raise ValueError("Vectors must be same 1 x N dimension to perform dot product")

- Test your code after generating two random 1 by 10 arrays. 

In [82]:
### Test Starts Here
X = np.random.randint(100, size=10)
Y = np.random.randint(100, size=10)
print(X)
print(Y)
dot = dot_product(X,Y)
assert np.dot(X, Y) == dot
dot

[13 97 52 26 51 97 34 12 18 58]
[ 5 79 91 20 94 14 30 32 16 78]


25348

- Consider three vectors ${\bf x}_1=(1,3), {\bf x}_2=(-1,5)$, and ${\bf x}_3=(0,7)$. 

    - Find the distance of each point from the origin.

    - Find the center of three points. 

    - Rotate the coordinates by 35 degress in counter clockwise. 

    - Magnify the area by 4 times. 

In [83]:
### Code Starts Here
origin = (0,0)
point1 = (1,3)
point2 = (-1,5)
point3 = (0,7)


def distance(x: tuple, y: tuple) -> int:
    """ Captures the distance between two points """
    x1, y1 = x
    x2, y2 = y
    return math.sqrt(pow(x2 - x1, 2) + pow(y2 - y1, 2))

def centre(coordinates: list) -> tuple:
    """ Finds the center between N points """
    length = len(points)
    if length <= 1:
        raise ValueError("Cannot find centre of less than two points, please input at least two points")
        
    x = y = 0
    for x_n, y_n in coordinates:
        x += x_n
        y += y_n
    return (x / length, y / length)


def rotate(coordinates: tuple, degrees: int) -> list:
    """ Rotates the input coordinates about the x axis and returns the new coordinates """
    x, y = coordinates
    cos = math.cos(math.radians(degrees))
    sin = math.sin(math.radians(degrees))
    x_coord = (x * cos) - y * sin
    y_coord = (y * cos) + (x * sin)
    return (x_coord, y_coord)

print(f"Distance from Origin for X1: {distance(origin, point1)}\n\t\t" \
      f"     for X2: {distance(origin, point2)}\n\t\t" \
      f"     for X3: {distance(origin, point3)}")

points = [point1, point2, point3]
print(f"Centre between the points: {centre([point1, point2, point3])}")
print(f"Rotations 35 degrees around Origin " \
      f"for X1: {rotate(point1, 35)}\n\t\t\t\t" \
      f"   for X2: {rotate(point2, 35)}\n\t\t\t\t" \
      f"   for X3: {rotate(point3, 35)}")
print(f"Volume magnification by 4: " \
      f"for X1: {(point1[0] * 4, point1[1])}\n\t\t\t" \
      f"   for X2: {(point2[0] * 4, point2[1])}\n\t\t\t" \
      f"   for X3: {(point3[0] * 4, point3[1])}")

Distance from Origin for X1: 3.1622776601683795
		     for X2: 5.0990195135927845
		     for X3: 7.0
Centre between the points: (0.0, 5.0)
Rotations 35 degrees around Origin for X1: (-0.9015772647641463, 3.0310325692180213)
				   for X2: (-3.687034226044222, 3.5221837850939126)
				   for X3: (-4.015035054457322, 5.7340643100229425)
Volume magnification by 4: for X1: (4, 3)
			   for X2: (-4, 5)
			   for X3: (0, 7)


### Problem 2
- Write a function `mat_product` to calculate the matrix product of two n by n arrays. For example:


$A = \begin{bmatrix} 1 & 3 & 0 \\ 2 & 0 & 2 \\ 1 & 1 & 4 \end{bmatrix}$ and $A\cdot A=\begin{bmatrix} 7 & 3 & 6 \\ 4 & 8 & 8 \\ 7 & 8 & 18 \end{bmatrix}$

In [84]:
def mat_product(v1: np.ndarray, v2: np.ndarray) -> np.ndarray:
    """ Calculates the Matrix Product of two N x N matrices """
    v1_row, v1_col = v1.shape
    v2_row, v2_col = v2.shape
    if v1.shape == v2.shape and v1_row == v1_col:  # Ensure shapes match and both are n x n
        product = list()
        v2_columns = [np.array([row[idx] for row in v2]) for idx in range(v2_col)]
        for i in range(v1_row):
            for j in range(v2_row):
                num = dot_product(v1[i], v2_columns[j])
                product.append(num)
        return np.array(product).reshape(v1_row, v2_col) 
    raise ValueError("Shapes do not match, or the matricies are not n x n")
    
A = np.array([1,3,0,2,0,2,1,1,4]).reshape(3,3)
mat_prod1 = mat_product(A, A)
np.testing.assert_array_equal(np.matmul(A, A), mat)
mat

array([[ 7,  3,  6],
       [ 4,  8,  8],
       [ 7,  7, 18]])

Test your code after generating two random 4 by 4 matrices, ${\bf X}$ and ${\bf Y}$.  

In [85]:
### Test Starts Here
X = np.random.randint(100, size=(4,4))
Y = np.random.randint(100, size=(4,4))
print(X)
print(Y)
mat_prod2 = mat_product(X,Y)
np.testing.assert_array_equal(np.matmul(X, Y), mat_prod2)
mat_prod2

[[96 62 32 19]
 [43 83 80 34]
 [54 23 90 54]
 [50 89  5  7]]
[[74 91 96  9]
 [49  1 79 13]
 [28 19 60  3]
 [59  1 90 28]]


array([[12159,  9425, 17744,  2298],
       [11495,  5550, 18545,  2658],
       [10829,  6701, 17261,  2567],
       [ 8614,  4741, 12761,  1818]])

- Transpose ${\bf X}$ and use the `mat_product` function to find the matrice of product: $Z={\bf X}^T\cdot{\bf Y}$

In [86]:
### Code Starts H
def transpose(matrix: np.ndarray) -> np.ndarray:
    """ Transposes the matrix """
    row, col = matrix.shape
    transpose = np.zeros(matrix.shape, dtype=int)
    for i in range(row):
        for j in range(col):
            transpose[i][j] = matrix[j][i]
    return transpose

X_T = transpose(X)
mat_prod3 = mat_product(X_T, Y)
print(f"Transpose of X:\n{X_T}")
print(f"Product of Transpose:\n{mat_prod3}")
np.testing.assert_array_equal(np.matmul(X_T, Y), mat_prod3)

Transpose of X:
[[96 43 54 50]
 [62 83 23 89]
 [32 80 90  5]
 [19 34 54  7]]
Product of Transpose:
[[13673  9855 20353  2985]
 [14550  6251 21899  4198]
 [ 9103  4707 15242  1738]
 [ 4997  2796  8380   971]]


Markdown $\alpha$<sup>2</sup>
Latex: $\alpha^2$

### Problem 3
- Write a function, `Det`, to find the determinant of n by n matrice, `EGval`, that finds the eigenvalue $\lambda$ and a function, `EGvec`, that finds the eigenvectors ${\bf x}$
- For the confirmation, use ${\bf A}=\begin{bmatrix} 1 & 2 \\ 2 & 4 \end{bmatrix}$.

In [87]:
### Det Code Starts Here ###
def Det(m: np.ndarray) -> int:
    """ Finds determinant of n x n matrix """
    if len(m.shape) == 1 and m.shape[0] == 1:  # Accounts for a (1,) passed
        return m[0]
    
    row, col = m.shape
    if row != col:  # Ensure matrix is N x N
        raise ValueError("Must be a N x N matrix to find the determinant")
    if row == 1:  # Base condition
        return m[0][0]
    
    det = 0.0
    top = m[0]  # Only have to iterate top row to find determinant of N x N matrix
    for i in range(row):
        offset = 1 if ((1 + i + 1) % 2 == 0) else -1
        leftover = np.array(
            [m[k][l] for k in range(row) for l in range(col) if k != 0 and l != i]
        ).reshape((row-1,col-1))
        det += offset * top[i] * Det(leftover)
    return det

A = np.array([1,2,2,4]).reshape((2,2))
print(Det(A))
assert np.linalg.det(A) == Det(A)

B = np.random.randint(100, size=(6,6))
det1 = np.linalg.det(B)
det2 = Det(B)
print(f"assert {det2} == {det1}")

0.0
assert -28845005526.0 == -28845005526.00009


In [88]:
### EGval Code Starts Here ###
### Eignvalues are solved by det(Lamba * Identity - A) = 0
def EGval(m: np.ndarray) -> tuple:
    """ Solves for the Eigenvalues of 2 x 2 matrices using the quadratic equation found here:
    https://en.wikipedia.org/wiki/Eigenvalue_algorithm#2%C3%972_matrices """
    row, col = m.shape
    if row != col or row != 2:
        raise ValueError("Solves for eigenvalues of only 2 x 2 matrices")
        
    tr = sum([m[i][i] for i in range(row)])
    gap = math.sqrt(math.pow(tr, 2) - 4 * Det(m))
    return ((tr - gap) / 2, (tr + gap) / 2)

egval1, egval2 = EGval(A)
print(f"Eigenvalues for vector A: {egval1}, {egval2}")
val1, val2= np.linalg.eigvals(A)
assert egval1 == vals[0]
assert egval2 == vals[1]

Eigenvalues for vector A: 0.0, 5.0


In [89]:
### EGvec Code Starts Here ###
identity = np.identity(2, dtype=int)

### First eigenvector 
print(f"Solving for eigenvector with the Eigenvalue of {egval1}")
mat1 = A - (egval1 * identity)  # Must equal zero when multiplied by x
print(f"A - Lambda*Identity =\n{mat1}")
egvec1 = np.array([-2,1])
print(f"Solve for linear equations using x = 1 and y = 2, or {egvec1}")
mat1 = mat1 * egvec1
mat1 = np.array([mat1[0][0] + mat1[0][1], mat1[1][0] + mat1[1][1]])
print(f"So eigenvector for the eigenvalue {egval1} is {egvec1} because (A - Lambda*Identity)*{egvec1} = {mat1}")

print("\n\n")

### Second eigenvector
print(f"Solving for eigenvector with the Eigenvalue of {egval2}")
mat2 = A - (egval2 * identity)  # Must equal zero when multiplied by x
print(f"A - Lambda*Identity =\n{mat2}")
egvec2 = np.array([1,2])
print(f"Solve for linear equations using x = 1 and y = 2, or {egvec1}")
mat2 = mat2 * egvec2.reshape((1,2))
mat2 = np.array([mat2[0][0] + mat2[0][1], mat2[1][0] + mat2[1][1]])
print(f"So eigenvector for the eigenvalue {egval2} is {egvec2} because (A - Lambda*Identity)*{egvec2} = {mat2}")

Solving for eigenvector with the Eigenvalue of 0.0
A - Lambda*Identity =
[[1. 2.]
 [2. 4.]]
Solve for linear equations using x = 1 and y = 2, or [-2  1]
So eigenvector for the eigenvalue 0.0 is [-2  1] because (A - Lambda*Identity)*[-2  1] = [0. 0.]



Solving for eigenvector with the Eigenvalue of 5.0
A - Lambda*Identity =
[[-4.  2.]
 [ 2. -1.]]
Solve for linear equations using x = 1 and y = 2, or [-2  1]
So eigenvector for the eigenvalue 5.0 is [1 2] because (A - Lambda*Identity)*[1 2] = [0. 0.]
